# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: update submodules' tags
      run: git submodule foreach --recursive 'git fetch --tags'
      
    - uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 16.5

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    
    
    - name: Bootstrap
      run: python bootstrap.py
      timeout-minutes: 3

    - name: Restore using netcore
      run: dotnet restore
      timeout-minutes: 5
    
    - name: Build
      run: MsBuild TDiffBackup.sln /t:Build /p:Configuration=Release
      timeout-minutes: 5

    - name: Test using netcore
      run: dotnet test
      timeout-minutes: 5
    
    - name: Install python deps
      run: python -m pip install --user requests bsdiff4
      timeout-minutes: 5
      
    - name: Run integration python test script
      run: python tests.py
      timeout-minutes: 20
     
